# 콘솔 로그 레벨 변경
logging:
  level:
    root: debug

# spring.application.name=hello-spring

# mybatis 연동 설정
mybatis:
  # mybatis 설정 파일 위치 지정
  config-location: classpath:mybatis-config.xml
  # mapper 파일들의 위치 지정
  mapper-locations: classpath:com/ktdsuniversity/edu/**/mapper/*Mapper.xml

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SPRING_BOOT
    password: 1234
  application:
    name: hello-spring
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp