## 콘솔 로그 레벨 변경
#logging:
#  level:
#    root: debug

# spring.application.name=hello-spring

# mybatis 연동 설정
mybatis:
  # mybatis 설정 파일 위치 지정
  config-location: classpath:mybatis-config.xml
  # mapper 파일들의 위치 지정
  mapper-locations: classpath:com/ktdsuniversity/edu/**/mapper/*Mapper.xml

spring:
  servlet:
    multipart: # 파일 업로드 용량 정책 설정
      # Spring Server가 한 번에 받을 수 있는 최대 용량
      max-file-size: 150MB
      # 파일 업로드를 할 수 있는 최대 용량
      max-request-size: 50MB
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SPRING_BOOT
    password: 1234
  application:
    name: hello-spring
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
app:
  jwt:
    issuer: hello-spring
    secret-key: 9dsadyu9q21jejasd821iasdjsac098210asncbjaod
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: TMDB
#    password: TMDB
#  application:
#    name: hello-spring
#  mvc:
#   view:
#     prefix: /WEB-INF/views/
#     suffix: .jsp